var hierarchy =
[
    [ "CI_Controller", null, [
      [ "C_Dashboard", "class_c___dashboard.html", null ],
      [ "C_Dashboard_new", "class_c___dashboard__new.html", null ],
      [ "C_Department", "class_c___department.html", null ],
      [ "C_Email", "class_c___email.html", null ],
      [ "C_Employee", "class_c___employee.html", null ],
      [ "C_Menu", "class_c___menu.html", null ],
      [ "C_Print", "class_c___print.html", null ],
      [ "C_Print_approved", "class_c___print__approved.html", null ],
      [ "C_Print_cn", "class_c___print__cn.html", null ],
      [ "C_Print_dn", "class_c___print__dn.html", null ],
      [ "C_Role", "class_c___role.html", null ],
      [ "C_Role_Access", "class_c___role___access.html", null ],
      [ "C_Role_Access", "class_c___role___access.html", null ],
      [ "C_User", "class_c___user.html", null ],
      [ "C_akun_dn", "class_c__akun__dn.html", null ],
      [ "C_approver", "class_c__approver.html", null ],
      [ "C_bank", "class_c__bank.html", null ],
      [ "C_bank_name", "class_c__bank__name.html", null ],
      [ "C_cicilan_dn", "class_c__cicilan__dn.html", null ],
      [ "C_cn", "class_c__cn.html", null ],
      [ "C_cn", "class_c__cn.html", null ],
      [ "C_company_to", "class_c__company__to.html", null ],
      [ "C_currency", "class_c__currency.html", null ],
      [ "C_department", "class_c__department.html", null ],
      [ "C_director", "class_c__director.html", null ],
      [ "C_director", "class_c__director.html", null ],
      [ "C_dn", "class_c__dn.html", null ],
      [ "C_dn", "class_c__dn.html", null ],
      [ "C_email_v2", "class_c__email__v2.html", null ],
      [ "C_finance", "class_c__finance.html", null ],
      [ "C_nama_account", "class_c__nama__account.html", null ],
      [ "C_reminder", "class_c__reminder.html", null ],
      [ "C_role_form", "class_c__role__form.html", null ],
      [ "C_section", "class_c__section.html", null ],
      [ "C_setting_approval", "class_c__setting__approval.html", null ],
      [ "C_setting_approval_new", "class_c__setting__approval__new.html", null ],
      [ "C_setting_approval_old", "class_c__setting__approval__old.html", null ],
      [ "C_source_information", "class_c__source__information.html", null ],
      [ "C_superior", "class_c__superior.html", null ],
      [ "C_sys_menu", "class_c__sys__menu.html", null ],
      [ "C_sys_role", "class_c__sys__role.html", null ],
      [ "C_sys_user", "class_c__sys__user.html", null ],
      [ "C_template", "class_c__template.html", null ],
      [ "C_tipe_transfer", "class_c__tipe__transfer.html", null ],
      [ "C_transfer_to", "class_c__transfer__to.html", null ],
      [ "C_transfer_to", "class_c__transfer__to.html", null ],
      [ "C_vat", "class_c__vat.html", null ],
      [ "C_video", "class_c__video.html", null ]
    ] ],
    [ "MY_Controller", null, [
      [ "Auth", "class_auth.html", null ]
    ] ]
];